# Generated by Django 5.2.3 on 2025-07-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractanalysis",
            old_name="upload_time",
            new_name="analysis_time",
        ),
        migrations.RenameField(
            model_name="contractanalysis",
            old_name="filename",
            new_name="file_name",
        ),
        migrations.AddField(
            model_name="contractanalysis",
            name="pdf_file",
            field=models.FileField(default="", upload_to="uploads/contracts/"),
            preserve_default=False,
        ),
    ]
